# Use the official Node.js image as a base
FROM node:18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json 
COPY src/web_server/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY src/web_server/ .

# Start the app
CMD ["npm", "start"]